controller_names:
  - gripper_trajectory_controller

gripper_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_joint_1_right
  state_publish_rate: 25.0
  action_monitor_rate: 10.0
  gains:
    gripper_joint_1_right:
      p: 10.0
      i: 0.0
      d: 0.0
