# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: all_zeros
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - linear_axis
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

  
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - linear_axis
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  - name: arm_controller_joint_traj
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - linear_axis
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - linear_axis
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  gains:
    linear_axis:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

gazebo_ros_control:
  pid_gains:
    linear_axis: { p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0 }
    joint_1: { p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0 }
    joint_2: { p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0 }
    joint_3: { p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0 }
    joint_4: { p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0 }
    joint_5: { p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0 }
    joint_6: { p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0 }














# arm_controller_joint_traj:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - linear_axis
#     - joint_1
#     - joint_2
#     - joint_3
#     - joint_4
#     - joint_5
#     - joint_6
#   gains:
#     linear_axis:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_1:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_2:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_3:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_4:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_5:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_6:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
# arm_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - linear_axis
#     - joint_1
#     - joint_2
#     - joint_3
#     - joint_4
#     - joint_5
#     - joint_6
#   gains:
#     linear_axis:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_1:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_2:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_3:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_4:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_5:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_6:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1