# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - six_dofra_planning_group_controller

  six_dofra_planning_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - linear_axis
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6