controller_list:
  - name: arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: sledge
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - linear_axis