controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_linear_axis_controller
    type: $(arg fake_execution_type)
    joints:
      - linear_axis
initial:  # Define initial robot poses per group
  - group: arm
    pose: Pick_Station
  - group: linear_axis
    pose: Home_1