gazebo_ros_control:
  pid_gains:
    linear_axis:
      p: 100
      i: 0.01
      d: 10
      i_clamp: 1
    joint_1:
      p: 100
      i: 0.01
      d: 10
      i_clamp: 1
    joint_2:
      p: 100
      i: 0.01
      d: 10
      i_clamp: 1
    joint_3:
      p: 100
      i: 0.01
      d: 10
      i_clamp: 1
    joint_4:
      p: 100
      i: 0.01
      d: 10
      i_clamp: 1
    joint_5:
      p: 100
      i: 0.01
      d: 10
      i_clamp: 1
    joint_6:
      p: 100
      i: 0.01
      d: 10
      i_clamp: 1